# Generated by Django 3.2.6 on 2023-10-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=60, unique=True),
        ),
    ]
