# Generated by Django 3.2.6 on 2023-10-24 11:14

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('story_title', models.CharField(max_length=100)),
                ('story_content', models.TextField()),
                ('story_description', models.CharField(max_length=400)),
                ('story_topic', models.CharField(max_length=60)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('story_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
