# Generated by Django 3.2.6 on 2023-10-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stories'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stories',
            table='stories',
        ),
    ]
