services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stories_db
      - POSTGRES_USER=dennis
      - POSTGRES_PASSWORD=dkamau476
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://dennis:dkamau476@localhost:5432/stories_db
    depends_on:
      - db
