# Generated by Django 3.2.6 on 2023-11-30 11:04

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_stories_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='story_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='story_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='story_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='story_topic',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story_description',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(default=api.models.generate_uuid, editable=False, max_length=60, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stories')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
