name: build-python

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.6

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r backend/requirements.txt

