name: build react-app

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: install dependencies
        run: npm install
        working-directory: frontend

      - name: Build React app
        run: npm run build
        working-directory: frontend

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build
